// Code generated by irpc v0.0.1 (h1:ZwdCknwkDvR5pWhGFCY...); DO NOT EDIT
// Source: github.com/nobonobo/diy-controller/service/service.go
package service

import (
	"context"
	"fmt"
	"github.com/marben/irpc/irpcgen"
)

var _ServiceIrpcId = irpcgen.ServiceId(0xb76dcdc0762cca7e)

// ServiceIrpcService provides [Service] interface over irpc
type ServiceIrpcService struct {
	impl Service
}

// NewServiceIrpcService returns new [irpcgen.Service] forwarding [Service] network calls to impl
func NewServiceIrpcService(impl Service) *ServiceIrpcService {
	return &ServiceIrpcService{
		impl: impl,
	}
}

// Id implements [irpcgen.Service] interface.
func (s *ServiceIrpcService) Id() irpcgen.ServiceId {
	return _ServiceIrpcId
}

// GetFuncCall implements [irpcgen.Service] interface
func (s *ServiceIrpcService) GetFuncCall(funcId irpcgen.FuncId) (irpcgen.ArgDeserializer, error) {
	switch funcId {
	case 0: // Gains
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			return func(ctx context.Context) irpcgen.Serializable {
				var resp _irpc_Service_GainsResp
				resp.p0 = s.impl.Gains()
				return resp
			}, nil
		}, nil
	case 1: // SetGains
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			var args _irpc_Service_SetGainsReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				s.impl.SetGains(args.s)
				return irpcgen.EmptySerializable{}
			}, nil
		}, nil
	case 2: // Settings
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			return func(ctx context.Context) irpcgen.Serializable {
				var resp _irpc_Service_SettingsResp
				resp.p0 = s.impl.Settings()
				return resp
			}, nil
		}, nil
	case 3: // SetSettings
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			var args _irpc_Service_SetSettingsReq
			if err := args.Deserialize(d); err != nil {
				return nil, err
			}
			return func(ctx context.Context) irpcgen.Serializable {
				s.impl.SetSettings(args.s)
				return irpcgen.EmptySerializable{}
			}, nil
		}, nil
	case 4: // Store
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			return func(ctx context.Context) irpcgen.Serializable {
				var resp _irpc_Service_StoreResp
				resp.p0 = s.impl.Store()
				return resp
			}, nil
		}, nil
	case 5: // Load
		return func(d *irpcgen.Decoder) (irpcgen.FuncExecutor, error) {
			return func(ctx context.Context) irpcgen.Serializable {
				var resp _irpc_Service_LoadResp
				resp.p0 = s.impl.Load()
				return resp
			}, nil
		}, nil
	default:
		return nil, fmt.Errorf("function '%d' doesn't exist on service '%s'", funcId, s.Id())
	}
}

// ServiceIrpcClient implements [Service] interface. It by forwards calls over network to [ServiceIrpcService] that provides the implementation.
type ServiceIrpcClient struct {
	endpoint irpcgen.Endpoint
}

func NewServiceIrpcClient(endpoint irpcgen.Endpoint) (*ServiceIrpcClient, error) {
	if err := endpoint.RegisterClient(_ServiceIrpcId); err != nil {
		return nil, fmt.Errorf("register failed: %w", err)
	}
	return &ServiceIrpcClient{endpoint: endpoint}, nil
}

// Gains implements [Service]
//
func (_c *ServiceIrpcClient) Gains() map[string]int32 {
	var resp _irpc_Service_GainsResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _ServiceIrpcId, 0, irpcgen.EmptySerializable{}, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}

// SetGains implements [Service]
func (_c *ServiceIrpcClient) SetGains(s map[string]int32) {
	var req = _irpc_Service_SetGainsReq{
		s: s,
	}
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _ServiceIrpcId, 1, req, &irpcgen.EmptyDeserializable{}); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
}

// Settings implements [Service]
func (_c *ServiceIrpcClient) Settings() map[string]int32 {
	var resp _irpc_Service_SettingsResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _ServiceIrpcId, 2, irpcgen.EmptySerializable{}, &resp); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
	return resp.p0
}

// SetSettings implements [Service]
func (_c *ServiceIrpcClient) SetSettings(s map[string]int32) {
	var req = _irpc_Service_SetSettingsReq{
		s: s,
	}
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _ServiceIrpcId, 3, req, &irpcgen.EmptyDeserializable{}); err != nil {
		panic(err) // to avoid panic, make your func return error and regenerate irpc code
	}
}

// Store implements [Service]
func (_c *ServiceIrpcClient) Store() error {
	var resp _irpc_Service_StoreResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _ServiceIrpcId, 4, irpcgen.EmptySerializable{}, &resp); err != nil {
		return err
	}
	return resp.p0
}

// Load implements [Service]
func (_c *ServiceIrpcClient) Load() error {
	var resp _irpc_Service_LoadResp
	if err := _c.endpoint.CallRemoteFunc(context.Background(), _ServiceIrpcId, 5, irpcgen.EmptySerializable{}, &resp); err != nil {
		return err
	}
	return resp.p0
}

type _irpc_Service_GainsResp struct {
	p0 map[string]int32
}

func (s _irpc_Service_GainsResp) Serialize(e *irpcgen.Encoder) error {
	if err := func(enc *irpcgen.Encoder, m map[string]int32) error {
		return irpcgen.EncMap(enc, m, "string", irpcgen.EncString, "int32", irpcgen.EncInt32)
	}(e, s.p0); err != nil {
		return fmt.Errorf("serialize type map[string]int32: %w", err)
	}
	return nil
}
func (s *_irpc_Service_GainsResp) Deserialize(d *irpcgen.Decoder) error {
	if err := func(dec *irpcgen.Decoder, m *map[string]int32) error {
		return irpcgen.DecMap(dec, m, "string", irpcgen.DecString, "int32", irpcgen.DecInt32)
	}(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type map[string]int32: %w", err)
	}
	return nil
}

type _irpc_Service_SetGainsReq struct {
	s map[string]int32
}

func (s _irpc_Service_SetGainsReq) Serialize(e *irpcgen.Encoder) error {
	if err := func(enc *irpcgen.Encoder, m map[string]int32) error {
		return irpcgen.EncMap(enc, m, "string", irpcgen.EncString, "int32", irpcgen.EncInt32)
	}(e, s.s); err != nil {
		return fmt.Errorf("serialize \"s\" of type map[string]int32: %w", err)
	}
	return nil
}
func (s *_irpc_Service_SetGainsReq) Deserialize(d *irpcgen.Decoder) error {
	if err := func(dec *irpcgen.Decoder, m *map[string]int32) error {
		return irpcgen.DecMap(dec, m, "string", irpcgen.DecString, "int32", irpcgen.DecInt32)
	}(d, &s.s); err != nil {
		return fmt.Errorf("deserialize s of type map[string]int32: %w", err)
	}
	return nil
}

type _irpc_Service_SettingsResp struct {
	p0 map[string]int32
}

func (s _irpc_Service_SettingsResp) Serialize(e *irpcgen.Encoder) error {
	if err := func(enc *irpcgen.Encoder, m map[string]int32) error {
		return irpcgen.EncMap(enc, m, "string", irpcgen.EncString, "int32", irpcgen.EncInt32)
	}(e, s.p0); err != nil {
		return fmt.Errorf("serialize type map[string]int32: %w", err)
	}
	return nil
}
func (s *_irpc_Service_SettingsResp) Deserialize(d *irpcgen.Decoder) error {
	if err := func(dec *irpcgen.Decoder, m *map[string]int32) error {
		return irpcgen.DecMap(dec, m, "string", irpcgen.DecString, "int32", irpcgen.DecInt32)
	}(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type map[string]int32: %w", err)
	}
	return nil
}

type _irpc_Service_SetSettingsReq struct {
	s map[string]int32
}

func (s _irpc_Service_SetSettingsReq) Serialize(e *irpcgen.Encoder) error {
	if err := func(enc *irpcgen.Encoder, m map[string]int32) error {
		return irpcgen.EncMap(enc, m, "string", irpcgen.EncString, "int32", irpcgen.EncInt32)
	}(e, s.s); err != nil {
		return fmt.Errorf("serialize \"s\" of type map[string]int32: %w", err)
	}
	return nil
}
func (s *_irpc_Service_SetSettingsReq) Deserialize(d *irpcgen.Decoder) error {
	if err := func(dec *irpcgen.Decoder, m *map[string]int32) error {
		return irpcgen.DecMap(dec, m, "string", irpcgen.DecString, "int32", irpcgen.DecInt32)
	}(d, &s.s); err != nil {
		return fmt.Errorf("deserialize s of type map[string]int32: %w", err)
	}
	return nil
}

type _irpc_Service_StoreResp struct {
	p0 error
}

func (s _irpc_Service_StoreResp) Serialize(e *irpcgen.Encoder) error {
	if err := func(enc *irpcgen.Encoder, v error) error {
		isNil := v == nil
		if err := irpcgen.EncIsNil(enc, isNil); err != nil {
			return fmt.Errorf("serialize isNil == %t: %w", isNil, err)
		}
		if isNil {
			return nil
		}
		_Error_0_ := v.Error()
		if err := irpcgen.EncString(enc, _Error_0_); err != nil {
			return fmt.Errorf("serialize \"v.Error()\" of type string: %w", err)
		}
		return nil
	}(e, s.p0); err != nil {
		return fmt.Errorf("serialize type error: %w", err)
	}
	return nil
}
func (s *_irpc_Service_StoreResp) Deserialize(d *irpcgen.Decoder) error {
	if err := func(dec *irpcgen.Decoder, s *error) error {
		var isNil bool
		if err := irpcgen.DecIsNil(dec, &isNil); err != nil {
			return fmt.Errorf("deserialize isNil: %w", err)
		}
		if isNil {
			return nil
		}
		var impl _error_Service_impl
		if err := irpcgen.DecString(dec, &impl._Error_0_); err != nil {
			return fmt.Errorf("deserialize \"_Error_0_\" string: %w", err)
		}
		*s = impl
		return nil
	}(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type error: %w", err)
	}
	return nil
}

type _error_Service_impl struct {
	_Error_0_ string
}

func (i _error_Service_impl) Error() string {
	return i._Error_0_
}

type _irpc_Service_LoadResp struct {
	p0 error
}

func (s _irpc_Service_LoadResp) Serialize(e *irpcgen.Encoder) error {
	if err := func(enc *irpcgen.Encoder, v error) error {
		isNil := v == nil
		if err := irpcgen.EncIsNil(enc, isNil); err != nil {
			return fmt.Errorf("serialize isNil == %t: %w", isNil, err)
		}
		if isNil {
			return nil
		}
		_Error_0_ := v.Error()
		if err := irpcgen.EncString(enc, _Error_0_); err != nil {
			return fmt.Errorf("serialize \"v.Error()\" of type string: %w", err)
		}
		return nil
	}(e, s.p0); err != nil {
		return fmt.Errorf("serialize type error: %w", err)
	}
	return nil
}
func (s *_irpc_Service_LoadResp) Deserialize(d *irpcgen.Decoder) error {
	if err := func(dec *irpcgen.Decoder, s *error) error {
		var isNil bool
		if err := irpcgen.DecIsNil(dec, &isNil); err != nil {
			return fmt.Errorf("deserialize isNil: %w", err)
		}
		if isNil {
			return nil
		}
		var impl _error_Service_impl
		if err := irpcgen.DecString(dec, &impl._Error_0_); err != nil {
			return fmt.Errorf("deserialize \"_Error_0_\" string: %w", err)
		}
		*s = impl
		return nil
	}(d, &s.p0); err != nil {
		return fmt.Errorf("deserialize type error: %w", err)
	}
	return nil
}
